### ISSUE TITLE
issue on running sms_py

### ISSUE THREAD

**Issue by 1alikadri** [CleverProgrammer/CP-Twilio-Python-Text-App#3]
Traceback (most recent call last):
  File "C:/Users/Mohammed Ali/AppData/Local/Programs/Python/Python37/send_sms.py", line 5, in <module>
    client = TwilioRestClient(account_sid, auth_token)
  File "C:\Users\Mohammed Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\twilio\base\obsolete.py", line 20, in new_func
    .format(func.__name__)
twilio.base.obsolete.ObsoleteException: TwilioRestClient has been removed from this version of the library. Please refer to current documentation for guidance.

i am having this issue please help me out

**Comment by sarveshggn** [comment]
Just replace TwilioRestClient with Client as it works with newer version of twilio.

**Comment by shaikayesha-sk** [comment]
from twilio.rest import Client  # Import using Client

# Replace these with your own Twilio account credentials
account_sid = "AC994237b93e91ce32c9a6917a5a1529a4"
auth_token = "4282f5115a35df78a81977365d8038ac"
my_cell = "+91 89195 36123"
my_twilio = "+14158959911"

client = Client(account_sid, auth_token)  # Use Client for newer versions

my_msg = 'Your message goes here...'

message = client.messages.create(to=my_cell, from_=my_twilio,
                                 body=my_msg)
